version: "3"
services:
  database:
    build:
      context: ./docker/db
    image: crowdevents-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=crowdevents
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    restart: always
    networks:
      - backend

  appserver:
    build: 
      context: ./
      dockerfile: docker/app/Dockerfile-postgres
    image: crowdevents-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=crowdevents
      - POSTGRES_HOSTNAME=database
      - POSTGRES_PORT=5432
    networks:
      - backend
    restart: always

networks:
  backend: